### PR TITLE
Create new PhotonStructDecoder

### PR DESCRIPTION
**Pull request by mcm001**
Closes https://github.com/Mechanical-Advantage/AdvantageScope/pull/181

Still TODO:
- [ ] Verify schema hashes
- [x] Actually plumb this into the rest of the code
- [x] Allow PhotonStructDecoder to use normal Struct types as nested members
- [x] Guarantee that `float64 x;` and `double x;` hash to the same thing

It's not pretty, but for an MVP it's not bad
image
https://github.com/Mechanical-Advantage/AdvantageScope/pull/181

### CODE REVIEW

**Comment by mcm001** [comment]
I can't drag and drop Translation/Transform3ds onto the field, but it seems like all other decoding works. the bytes consumed member also needs to be trimmed off.
https://github.com/user-attachments/assets/5d2ac990-479b-4545-9616-df84dd5b814d

**Comment by mcm001** [comment]
This should be like 90% of the way to feature complete, but I haven't had a chance to go through and clean-up code yet.

**Comment by jwbonner** [comment]
I updated to the latest commit on `main`, and did a little bit of cleanup. Is there anything major still missing? If not, I'm planning an AdvantageScope release later today and it would be nice to include this feature given the PhotonVision release yesterday.

**Comment by mcm001** [comment]
I don't think there are any blocking features missing. I did want to add schema hash checking, but if I'm getting the schema UUID straight from the source already I don't see a reason to double verify it. I'd like to test once more with photon beta 1 before merging out of paranoia then I'm good to go (I'll be out at work for the next 10 hours fya)

Thank you for cleaning this up!

**Comment by jwbonner** [comment]
No problem, I'm not planning to release anything until later tonight anyway.

**Comment by jwbonner** [comment]
I did a quick test with the PhotonVision beta running in test mode, and it seems to look OK? I'll probably go ahead and merge unless you have an objection.

Screenshot 2024-11-11 at 11 15 49 PM

**Comment by mcm001** [comment]
Works for me in test mode here. Seeeeennnnnndddd it

**Pull request merged**
