### PR TITLE
Support live logging roboRIO via USB

### PR DESCRIPTION
**Pull request by jonahsnider**
Adds support for live logging a roboRIO via USB.

Haven't tested this.

Also, you should strongly consider using a formatting tool like [Prettier](https://prettier.io/) in this project to automatically enforce code style. I'd be happy to PR this if you'd like.

### CODE REVIEW

**Comment by jonahb55** [comment]
This definitely seems like a useful feature. (Our team always tethers over ethernet, so we just never thought about this.)

It seems like this might be better addressed through the preferences window though, since the RIO address is used both for live logging and connecting over SSH. The perfect solution would probably be to automatically search through possible addresses (like GradleRIO does when deploying), but setting that up to be robust is a more substantial project. That might be a good feature to add during the offseason. In the meantime, I tried adding an extra checkbox to the preferences which sets the IP address for connecting over USB, while remembering the normal address. At the start of an event, the user just needs to set this once for all of the networking functions to work properly. Does this seem like a reasonable solution?

https://user-images.githubusercontent.com/47046556/158071891-314a83ba-816f-41b7-b4b2-57a0711f125b.mov

Also, setting up a proper formatter has been on my list for a while. I'll see what I can do.

**Comment by jonahsnider** [comment]
> It seems like this might be better addressed through the preferences window though, since the RIO address is used both for live logging and connecting over SSH.

This is what we've been doing to test, but we often forget to change the IP in between wired & wireless test sessions.

> The perfect solution would probably be to automatically search through possible addresses (like GradleRIO does when deploying), but setting that up to be robust is a more substantial project.

I agree, this seems like the best option for UX. I spoke to the WPILib authors and this logic is actually not too complex to implement. SysID does it without using GradleRIO, it just pings a few known IP addresses (`10.TE.AM.2`, `172.22.11.2`, etc) until one responds. It also attempts reading the IP from the driver station if all-else fails but that seems unnecessary.

I will look into implementing this logic and perhaps making another PR to add it to Advantage Scope.

> At the start of an event, the user just needs to set this once for all of the networking functions to work properly. Does this seem like a reasonable solution?

This is definitely an improvement. Would the value of the "USB?" checkbox be persisted between app restarts? Always having it be unchecked on app start would work well for us since we don't do USB debugging sessions very frequently.

> Edit: The formatter is now set up.

Nice!

**Comment by jonahb55** [comment]
> I will look into implementing this logic and perhaps making another PR to add it to Advantage Scope.

I agree that this shouldn't be especially difficult in principle - my main concern is making sure that errors/disconnects/reconnects are handled gracefully. I spent enough time getting the current system to (sort of) work reliably that I'd want to make sure this system is very solid. That might also involve some larger restructuring; there are currently a lot of miscellaneous events going back and forth between the renderer and preload that could probably be simplified.

> Would the value of the "USB?" checkbox be persisted between app restarts?

As of right now, the value is persistent between app restarts. As long as it's part of preferences, I think that resetting it on restart would just be more confusing since that's not consistent with the behavior of the other preferences. Maybe it would work better as a separate toggle in the menu bar? That would mean that it's still correctly applied to both live logging and SSH connections. I can play with setting something up and see how it looks.

**Comment by jonahb55** [comment]
Sorry for the delay on this - I've had a busy week of other robot work. I tried adding a toggle to the menu bar that applies to both live logging and SSH. It also resets when the application restarts. The result is similar to your original approach, though the little bit of persistence means you don't need to request the USB mode every time you connect. If this seems like a satisfactory solution, I can do a full release with it

https://user-images.githubusercontent.com/47046556/158926087-f02c2da9-4c28-4b4c-85c4-fb11e28130b9.mp4

**Comment by jonahsnider** [comment]
This looks great! Thanks for your work on implementing this.

**Comment by jonahb55** [comment]
I just released [v1.17.0](https://github.com/Mechanical-Advantage/AdvantageScope/releases/tag/v1.17.0), which includes the toggle in the menu bar.

**Pull request closed without merging**
